language: ruby
rvm:
  - 2.0.0

sudo: required

addons:
  apt:
    update: true

before_install:
  - sudo apt-get install -y graphicsmagick

before_script:
  - nvm install node

script:
  - cd src
  - bundle install
  - npm install
  - cd ..

after_script:
  - ./make-dist
