language: ruby
rvm:
  - 2.5.0

sudo: required

addons:
  apt:
    update: true

before_install:
  - sudo apt-get install -y graphicsmagick
  - gem update --system
  - gem install bundler

before_script:
  - nvm install node v10

script:
  - cd src
  - bundle install
  - npm install
  - cd ..

after_script:
  - ./make-dist
